"""added shootout saves

Revision ID: 0d715fe39d9f
Revises: 6667b320e3ef
Create Date: 2021-11-27 21:12:02.317924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d715fe39d9f'
down_revision = '6667b320e3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shootout_sheet', sa.Column('evasion_save', sa.Integer(), nullable=True))
    op.add_column('shootout_sheet', sa.Column('mental_save', sa.Integer(), nullable=True))
    op.add_column('shootout_sheet', sa.Column('physical_save', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shootout_sheet', 'physical_save')
    op.drop_column('shootout_sheet', 'mental_save')
    op.drop_column('shootout_sheet', 'evasion_save')
    # ### end Alembic commands ###
