"""new column

Revision ID: 4621f8888df3
Revises: 216a408859e8
Create Date: 2021-05-16 01:23:20.956235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4621f8888df3'
down_revision = '216a408859e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('caption', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'caption')
    # ### end Alembic commands ###
