"""empty message

Revision ID: 6667b320e3ef
Revises: d333ed909e44
Create Date: 2021-10-24 18:19:16.578971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6667b320e3ef'
down_revision = 'd333ed909e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beatcops_sheet', sa.Column('exert', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beatcops_sheet', 'exert')
    # ### end Alembic commands ###
