"""empty message

Revision ID: d333ed909e44
Revises: 6ec04f161548
Create Date: 2021-10-06 17:30:37.096272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd333ed909e44'
down_revision = '6ec04f161548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beatcops_sheet', sa.Column('evasion_save', sa.Integer(), nullable=True))
    op.add_column('beatcops_sheet', sa.Column('mental_save', sa.Integer(), nullable=True))
    op.add_column('beatcops_sheet', sa.Column('physical_save', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beatcops_sheet', 'physical_save')
    op.drop_column('beatcops_sheet', 'mental_save')
    op.drop_column('beatcops_sheet', 'evasion_save')
    # ### end Alembic commands ###
