from wtforms import Form, StringField, IntegerField, SelectField
from wtforms.validators import DataRequired, InputRequired, Length

class SheetForm(Form):
    name = StringField('name', validators=[DataRequired(), Length(max=128)])
    character_class = StringField('character_class', validators=[DataRequired(), Length(max=128)])
    background = StringField('background', validators=[DataRequired(), Length(max=128)])
    level = IntegerField('level', validators=[InputRequired()])
    xp = IntegerField('xp', validators=[InputRequired()])
    max_hp = IntegerField('max_hp', validators=[InputRequired()])
    current_hp = IntegerField('current_hp', validators=[InputRequired()])
    system_strain = IntegerField('system_strain', validators=[InputRequired()])
    ac = IntegerField('ac', validators=[InputRequired()])
    strength = IntegerField('strength', validators=[InputRequired()])
    dexterity = IntegerField('dexterity', validators=[InputRequired()])
    constitution = IntegerField('constitution', validators=[InputRequired()])
    intelligence = IntegerField('intelligence', validators=[InputRequired()])
    wisdom = IntegerField('wisdom', validators=[InputRequired()])
    charisma = IntegerField('charisma', validators=[InputRequired()])
    administer = IntegerField('administer', validators=[InputRequired()])
    cast_magic = IntegerField('cast_magic', validators=[InputRequired()])
    connect = IntegerField('connect', validators=[InputRequired()])
    exert = IntegerField('exert', validators=[InputRequired()])
    fix = IntegerField('fix', validators=[InputRequired()])
    heal = IntegerField('heal', validators=[InputRequired()])
    horsemanship = IntegerField('horsemanship', validators=[InputRequired()])
    know = IntegerField('know', validators=[InputRequired()])
    know_magic = IntegerField('know_magic', validators=[InputRequired()])
    lead = IntegerField('lead', validators=[InputRequired()])
    notice = IntegerField('notice', validators=[InputRequired()])
    perform = IntegerField('perform', validators=[InputRequired()])
    punch = IntegerField('punch', validators=[InputRequired()])
    sail = IntegerField('sail', validators=[InputRequired()])
    shoot = IntegerField('shoot', validators=[InputRequired()])
    sneak = IntegerField('sneak', validators=[InputRequired()])
    stab = IntegerField('stab', validators=[InputRequired()])
    talk = IntegerField('talk', validators=[InputRequired()])
    trade = IntegerField('trade', validators=[InputRequired()])
    work = IntegerField('work', validators=[InputRequired()])
    submit = StringField('submit', validators=[InputRequired()])
    notes = StringField('notes')


class WeaponForm(Form):
    weapon = IntegerField('weapon', validators=[InputRequired()])
    delete = IntegerField('delete', validators=[InputRequired()])

